web: gunicorn {{ cookiecutter.repo_name }}.heroku -w 4 --settings={{ cookiecutter.repo_name }}.settings.prod --log-file -
celery: python manage.py celery worker -c 4 --loglevel=INFO --settings={{ cookiecutter.repo_name }}.prod
celerybeat: python manage.py celerybeat --settings={{ cookiecutter.repo_name }}.prod
